"""add_user_status_warning_friend

Revision ID: 2231b8d79f77
Revises: 4714b6c2b4a5
Create Date: 2026-05-15 03:43:49.913938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2231b8d79f77'
down_revision: Union[str, Sequence[str], None] = '4714b6c2b4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'friend_id', name='uq_user_friend')
    )
    op.create_index(op.f('ix_user_friends_friend_id'), 'user_friends', ['friend_id'], unique=False)
    op.create_index(op.f('ix_user_friends_id'), 'user_friends', ['id'], unique=False)
    op.create_index(op.f('ix_user_friends_user_id'), 'user_friends', ['user_id'], unique=False)
    op.create_table('user_warnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_warnings_id'), 'user_warnings', ['id'], unique=False)
    op.create_index(op.f('ix_user_warnings_user_id'), 'user_warnings', ['user_id'], unique=False)
    op.add_column('users', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.drop_index(op.f('ix_user_warnings_user_id'), table_name='user_warnings')
    op.drop_index(op.f('ix_user_warnings_id'), table_name='user_warnings')
    op.drop_table('user_warnings')
    op.drop_index(op.f('ix_user_friends_user_id'), table_name='user_friends')
    op.drop_index(op.f('ix_user_friends_id'), table_name='user_friends')
    op.drop_index(op.f('ix_user_friends_friend_id'), table_name='user_friends')
    op.drop_table('user_friends')
    # ### end Alembic commands ###
