"""add_comment_thanks

Revision ID: 4714b6c2b4a5
Revises: 60a4179b45d9
Create Date: 2026-05-15 03:40:02.378920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4714b6c2b4a5'
down_revision: Union[str, Sequence[str], None] = '60a4179b45d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_thanks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'user_id', name='uq_comment_user_thanks')
    )
    op.create_index(op.f('ix_comment_thanks_comment_id'), 'comment_thanks', ['comment_id'], unique=False)
    op.create_index(op.f('ix_comment_thanks_id'), 'comment_thanks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_thanks_id'), table_name='comment_thanks')
    op.drop_index(op.f('ix_comment_thanks_comment_id'), table_name='comment_thanks')
    op.drop_table('comment_thanks')
    # ### end Alembic commands ###
