"""add_friend_status

Revision ID: 5182c0ef6684
Revises: fa70e6484961
Create Date: 2026-05-15 04:29:09.990448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5182c0ef6684'
down_revision: Union[str, Sequence[str], None] = 'fa70e6484961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_friends', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_friends', 'status')
    # ### end Alembic commands ###
