"""add_registration_code

Revision ID: ae3d20f63b47
Revises: ebc143126255
Create Date: 2026-05-15 05:38:22.369285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae3d20f63b47'
down_revision: Union[str, Sequence[str], None] = 'ebc143126255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_codes_email'), 'registration_codes', ['email'], unique=False)
    op.create_index(op.f('ix_registration_codes_id'), 'registration_codes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registration_codes_id'), table_name='registration_codes')
    op.drop_index(op.f('ix_registration_codes_email'), table_name='registration_codes')
    op.drop_table('registration_codes')
    # ### end Alembic commands ###
