"""add_private_message

Revision ID: ebc143126255
Revises: 5182c0ef6684
Create Date: 2026-05-15 05:09:07.547345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebc143126255'
down_revision: Union[str, Sequence[str], None] = '5182c0ef6684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('private_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_private_messages_id'), 'private_messages', ['id'], unique=False)
    op.create_index(op.f('ix_private_messages_recipient_id'), 'private_messages', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_private_messages_sender_id'), 'private_messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_private_messages_sender_id'), table_name='private_messages')
    op.drop_index(op.f('ix_private_messages_recipient_id'), table_name='private_messages')
    op.drop_index(op.f('ix_private_messages_id'), table_name='private_messages')
    op.drop_table('private_messages')
    # ### end Alembic commands ###
